spring.application.name=backen
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/iskolarium-db
spring.datasource.username=postgres
spring.datasource.password=159357

# Hibernate settings (This tells Spring to automatically create the tables based on your code)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect